### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by anubra266** [project44/manifest#104]
Just played around with tooltips on the [site](https://www.manifestdesignsystem.com/docs/components/tooltip), and after initial load, they don't show when trigger is hovered, then when you leave the trigger they show slightly then leave. They behave well after you revisit the trigger.

https://user-images.githubusercontent.com/30869823/192077353-7bd0cf1c-f661-49f2-85b5-f26cf559f15a.mp4

**Comment by bclark-p44** [comment]
Thanks for catching this @anubra266. I will work on a fix soon!

**Comment by bclark-p44** [comment]
This has been resolved in the 2.6.3 release!
