### ISSUE TITLE
[Bug]: MultiSelect TypeScript Error

### ISSUE THREAD

**Issue by stv8** [project44/manifest#362]
### Description

The example provided in the manifest docs for the `<MultiSelect>` components has a type error 

```
TS2769: No overload matches this call.   Overload 1 of 2, '(props: Omit<HTMLProps<Options<As<any>>>, keyof MultiSelectOptions<"label">> & Omit<MultiSelectOptions<"label">, "as"> & Required<...>): Element | null', gave the following error.     Type 'Dispatch<SetStateAction<Set<string>>>' is not assignable to type '(keys: Selection) => any'.       Types of parameters 'value' and 'keys' are incompatible.         Type 'Selection' is not assignable to type 'SetStateAction<Set<string>>'.           Type 'string' is not assignable to type 'SetStateAction<Set<string>>'.   Overload 2 of 2, '(props: Props<MultiSelectOptions<"label">>): Element | null', gave the following error.     Type 'Dispatch<SetStateAction<Set<string>>>' is not assignable to type '(keys: Selection) => any'. 
```

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/5158539/235506703-e75470ca-7642-4261-882b-643fb217d00c.png">

### Link to reproduction

n/a

### Steps to reproduce

- Copy Paste the example from https://www.manifestdesignsystem.com/inputs/multi-select into a project
- Observe Type Error

### Code of Conduct

- [X] I agree to the [Code of Conduct](https://github.com/project44/manifest/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] I have reviewed the [current issues](https://github.com/project44/manifest/issues) for duplicate tickets.

**Comment by stv8** [comment]
Notes from meeting with @bclark-p44 

We need to add the `Selection` type available which is defined as 

`type Selection = 'all' | Set<Key>;`

**Comment by vivek-p44** [comment]
@aamir-p44 @vitaliy-p44 @smartinelli-p44  The url mentioned here seems to be not reachable, and i was also not able to find this particular component in code as well. Is there's anyone who can help with information whether we are currently using it or not ?

**Comment by vivek-p44** [comment]
This code is deprecated and no longer is in use, so closing this.

**Comment by stv8** [comment]
@vivek-p44 Here's the updated link to the `MultiSelect` component 

https://project44.github.io/manifest/inputs/multi-select
