### ISSUE TITLE
[Bug]: Clicking the Checkbox in ListBox does not fire change handler

### ISSUE THREAD

**Issue by p44dyoachim** [project44/manifest#404]
### Description

When using ListBox with selections, clicking the Checkbox element does not fire the change callback. Clicking the label does fire the callback however

### Link to reproduction

https://project44.github.io/manifest/data-display/list-box#selection

### Steps to reproduce

Click text label portion of ListBox
Note checkbox selection changes

Click Checkbox portion of ListBox
Note checkbox selection does not change

### Code of Conduct

- [X] I agree to the [Code of Conduct](https://github.com/project44/manifest/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] I have reviewed the [current issues](https://github.com/project44/manifest/issues) for duplicate tickets.

**Comment by danielrobertson** [comment]
It looks like the existing implementation was done using this Adobe Aria hook https://react-spectrum.adobe.com/react-aria/useListBox.html#complex-options

But `useListBox` hook not intended to support interactive children (`input` checkboxes for example) and recommends using `useGridList` hook if using interactive elements for accessibility reasons, so I will begin that refactor ASAP to this hook https://react-spectrum.adobe.com/react-aria/useGridList.html
