### ISSUE TITLE
[Bug]: Dialog throws console error 

### ISSUE THREAD

**Issue by danielrobertson** [project44/manifest#425]
### Description

Dialog close throws console error 
<img width="933" alt="image" src="https://github.com/project44/manifest/assets/3459902/c09c73f0-0186-457d-8320-fe9218d6a4f8">

Coming from react-aria: known issue https://github.com/adobe/react-spectrum/issues/4186#issuecomment-1587235603

### Link to reproduction

https://project44.github.io/manifest/overlays/dialog/

### Steps to reproduce

https://project44.github.io/manifest/overlays/dialog/

Open then close 

### Code of Conduct

- [X] I agree to the [Code of Conduct](https://github.com/project44/manifest/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] I have reviewed the [current issues](https://github.com/project44/manifest/issues) for duplicate tickets.

**Comment by vitaliy-p44** [comment]
already fixed
