### ISSUE TITLE
[Feature Request]: Autocomplete Label is cropped with 3 dot

### ISSUE THREAD

**Issue by ShubhamBhagat-p44** [project44/manifest#492]
### Description

![image](https://github.com/project44/manifest/assets/133108657/15eaa84f-87c3-4b45-a24b-e42500a7e4c9)

As seen in above image the No options Available text is getting cropped 

### Examples

https://movement.project44.com/network/root-cause-analysis?rcaView=Overview&dateType%5B0%5D=TRACKING_END_DATE&dates%5B0%5D=1691645782388&dates%5B1%5D=1699421782388&errorType=tracking

1. In above page go to filters
2. Select carrier filter
3. Search for asdasd. 

### Code of Conduct

- [X] I agree to the [Code of Conduct](https://github.com/project44/manifest/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] I have reviewed the [current issues](https://github.com/project44/manifest/issues) for duplicate tickets.

**Comment by vivek-p44** [comment]
Hi @ShubhamBhagat-p44 thanks for raising this well detailed issue, i went ahead and checked the code. This seems to be an issue on MWA code itself [Autocomplete component](https://github.com/project44/micro-webapps/blob/master/libs/analytics-filters-utils/src/components/common/Autocomplete/index.tsx#L94) there's a property of `max-width : 165px` which is causing text to overflow and show ellipsis.

If we increase width by few pixels it will be able to accommodate this length of text as well. Do let me know if you need any further help on this.

REF:- 
<img width="1728" alt="Screenshot 2023-11-08 at 4 46 02 PM" src="https://github.com/project44/manifest/assets/147403156/7bbba374-5d24-41fe-b3f8-6e53b432cd64">
